MALI: Build fixup when using O= w/ kernel builds
When using O= arguments, the wildcard check for
mali_kbase_ipa_vinstr_g71.c runs into trouble and does not get
enabled, causing the following build error:

drivers/built-in.o: In function `kbase_ipa_model_ops_find':
/home/docker/kernel/drivers/gpu/arm_gpu/ipa/mali_kbase_ipa.c:68: undefined reference to `kbase_g71_ipa_model_ops'
/home/docker/kernel/drivers/gpu/arm_gpu/ipa/mali_kbase_ipa.c:68: undefined reference to `kbase_g71_ipa_model_ops'
/home/docker/kernel/drivers/gpu/arm_gpu/ipa/mali_kbase_ipa.c:68: undefined reference to `kbase_g71_ipa_model_ops'
make[1]: *** [vmlinux] Error 1

So since the mali_kbase_ipa_vinstr_g71.c is present in the code
(no plans for it to come and go here), just remove the wildcard
checks and make sure it gets included into the build.

Reported-by: Dmitry Shmidt <dimitrysh@google.com>
Signed-off-by: John Stultz <john.stultz@linaro.org>